name: dotnet-setup
description: Setup .NET environment

inputs:
  dotnet-version:
    description: The .NET SDK version to use
    required: false
    default: '9.0.300'
  git-fetch-depth:
    description: The depth of the git fetch
    required: false
    default: "1"
  
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.git-fetch-depth }}
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    - name: install dependencies
      shell: bash
      run: dotnet restore
