name: Docker Publish to GHCR

inputs:
  version:
    required: true
    type: string
  token:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.version }}
    
    - name: Convert repository name to lowercase
      shell: bash
      id: repo
      run: |
        repo_lower=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        echo "repo=$repo_lower" >> $GITHUB_OUTPUT

    - name: Set up Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ghcr.io/${{ github.repository }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ steps.repo.outputs.repo }}:${{ inputs.version }}
          ghcr.io/${{ steps.repo.outputs.repo }}:latest
