name: Lint Go Code
description: Runs static code analysis on Go code using staticcheck

inputs:
  go-version:
    description: Go version to use
    required: false
    default: '1.24'

runs:
  using: 'composite'
  steps:
    - name: Set up Go
      uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/go/setup@feature/kind-test
      with:
        go-version: ${{ inputs.go-version }}

    - name: Run StaticCheck
      uses: dominikh/staticcheck-action@feature/kind-test.3.0
      with:
        install-go: false
        output-format: stylish
