name: Grype Scan

inputs:
  version:
    required: true
    type: string
  token:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    
    - name: Convert repository name to lowercase
      shell: bash
      id: repo
      run: |
        repo_lower=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        echo "repo=$repo_lower" >> $GITHUB_OUTPUT

    - name: Install Grype
      shell: bash
      run: |
        curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

    - name: Scan Docker image with Grype
      shell: bash
      run: |
        IMAGE=ghcr.io/${{ steps.repo.outputs.repo }}:${{ inputs.version }}
        echo "Scanning image: $IMAGE"
        grype $IMAGE -o table