name: Node.js Unit Tests
description: "Runs unit tests for a Node.js project using Jest and uploads the results."
    
inputs:
  test-command:
    description: "Command to run unit tests"
    required: false
    default: 'npm test'
    type: string
  node-version:
    description: "Node.js version to use"
    required: false
    default: '20'
    type: string

  working-directory:
    description: "Project root directory"
    required: false
    default: '.'
    type: string

outputs:
  coverage-report:
    description: "Coverage report file"
    value: coverage/cobertura-coverage.xml


runs:
  using: composite
  steps:
    - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/setup@patch-1
      with:
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.working-directory }}

    # This step will used to run unit test
    - name: Run Unit Tests
      run: ${{ inputs.test-command }}
      continue-on-error: true
      shell: bash

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/junit.xml
    
    - name: Annotate test failures
      uses: dorny/test-reporter@v1
      with:
        name: Jest Tests
        path: test-results/junit.xml
        reporter: jest-junit
        fail-on-error: false

