name: Node.js Unit Tests
description: "Runs unit tests for a Node.js project using Jest and uploads the results."
    
inputs:
  test-command:
    description: "Command to run unit tests"
    required: false
    default: 'npm test'
    type: string
  continue-on-error:
    description: "Continue on error for unit tests"
    required: false
    default: true
    type: boolean



outputs:
  coverage-report:
    description: "Coverage report file"
    value: coverage/cobertura-coverage.xml


runs:
  using: composite
  steps:
    # This step will used to run unit test
    - name: Run Unit Tests
      run: ${{ inputs.test-command }}
      continue-on-error: true
      shell: bash

    - name: Upload test results
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: test-results/junit.xml
    
    - name: Annotate test failures
      uses: dorny/test-reporter@v1
      with:
        name: Jest Tests
        path: test-results/junit.xml
        reporter: jest-junit
        fail-on-error: false

    - name: Summarize Jest Results
      shell: bash
      run: |
          if [[ ! -f jest-report.json ]]; then
            echo "## 🧪 Jest Unit Test Report" > summary.md
            echo "- ⚠️ No Jest report found. Was Jest run with --json?" >> summary.md
          else
            PASSED=$(jq '.numPassedTests' jest-report.json)
            FAILED=$(jq '.numFailedTests' jest-report.json)
            TOTAL=$(jq '.numTotalTests' jest-report.json)

            echo "## 🧪 Jest Unit Test Report" > summary.md
            echo "- 🟢 Passed: $PASSED" >> summary.md
            echo "- 🔴 Failed: $FAILED" >> summary.md
            echo "- 📊 Total: $TOTAL" >> summary.md
          fi

    
    - name: Upload ESLint Summary
      uses: actions/upload-artifact@v4
      with:
        name: jest-summary
        path: summary.md