name: build
description: Lint C# code using CSharpier

inputs:
  app-name:
    description: Application name to lint
    required: true
  dotnet-version:
    description: The .NET SDK version to use
    required: false
    default: '9.0.300'
  git-fetch-depth:
    description: The depth of the git fetch
    required: false
    default: "1"
  restore:
    description: Whether to restore dotnet tools before linting
    required: false
    default: "true"
  
runs:
  using: composite
  steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: ${{ inputs.git-fetch-depth }}
    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
    
    - name: Lint ${{ inputs.app-name }}
      if: ${{ inputs.restore == 'false' }}
      shell: bash
      run: |
        ls -al
        echo "installing roslynator tool"
        dotnet tool install --global roslynator.dotnet.cli
        which roslynator
        echo "roslynator analyze this solution"
        roslynator analyze

    - name: Lint ${{ inputs.app-name }}
      if: ${{ inputs.restore == 'true' }}
      shell: bash
      run: |
        echo "Restoring project tools"
        dotnet tool restore
        dotnet roslynator analyze
    