name: Trivy Scan Action
description: |
  This action scans a Docker image using Trivy and reports vulnerabilities.
  It logs in to the GitHub Container Registry, converts the repository name to lowercase,
  and generates a summary of critical and high vulnerabilities found in the image.

inputs:
  version:
    description: 'Docker image version to scan'
    required: true
    type: string
    default: 'latest'
  token:
    required: true
    type: string
  severity:
    required: false
    type: string
    default: 'CRITICAL,HIGH'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    
    - name: Download Trivy
      shell: bash
      run: |
        TRIVY_VERSION=0.50.1
        curl -sfL https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.tar.gz -o trivy.tar.gz
        tar -xzf trivy.tar.gz
        sudo mv trivy /usr/local/bin/
        trivy --version

    - name: Run Trivy Scan
      shell: bash
      run: |
        IMAGE=ghcr.io/${{ steps.repo.outputs.repo }}:${{ inputs.version }}
        trivy image --format table --exit-code 0 \
          --vuln-type os,library \
          --severity "${{ inputs.severity }}" \
          --username "${{ github.actor }}" \
          --password "${{ inputs.token }}" \
          $IMAGE | tee trivy-report.txt

    - name: Trivy Summary
      shell: bash
      run: |
        CRITICAL=$(grep -c 'CRITICAL' trivy-report.txt || true)
        HIGH=$(grep -c 'HIGH' trivy-report.txt || true)

        echo "## 🛡️ Trivy Scan" >> $GITHUB_STEP_SUMMARY
        echo "- 🚨 Critical: $CRITICAL" >> $GITHUB_STEP_SUMMARY
        echo "- ⚠️ High: $HIGH" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "<details><summary>📄 View Raw Report (truncated)</summary>" >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        head -n 100 trivy-report.txt >> $GITHUB_STEP_SUMMARY
        echo '```' >> $GITHUB_STEP_SUMMARY
        echo "</details>" >> $GITHUB_STEP_SUMMARY
