name:  

inputs:
  version:
    description: 'Docker image version to scan'
    required: true
    type: string
    default: 'latest'
  token:
    required: true
    type: string
  severity:
    required: false
    type: string
    default: 'CRITICAL,HIGH'

runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    
    - name: Convert repository name to lowercase
      shell: bash
      id: repo
      run: |
        repo_lower=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        echo "repo=$repo_lower" >> $GITHUB_OUTPUT

    - name: Scan Docker image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ghcr.io/${{ steps.repo.outputs.repo }}:${{ inputs.version }}
        format: table
        exit-code: 0
        output: trivy-report.txt
        vuln-type: os,library
        severity: ${{ inputs.severity }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    
    - name: Summarize Trivy Report
      shell: bash
      run: |
        CRITICAL=$(grep -c 'CRITICAL' trivy-report.txt || true)
        HIGH=$(grep -c 'HIGH' trivy-report.txt || true)

        echo "## 🛡️ Trivy Scan" > summary.md
        echo "- 🚨 Critical: $CRITICAL" >> summary.md
        echo "- ⚠️ High: $HIGH" >> summary.md
        echo "" >> summary.md
        echo "<details><summary>📄 View Raw Report</summary>" >> summary.md
        echo '' >> summary.md
        echo '```' >> summary.md
        cat trivy-report.txt >> summary.md
        echo '```' >> summary.md
        echo '</details>' >> summary.md

    - name: Upload Trivy Summary
      uses: actions/upload-artifact@v4
      with:
        name: trivy-summary
        path: summary.md