name: security-scan
description: Scan Docker images for vulnerabilities using Snyk

inputs:
  registry:
    description: 'Container registry. Example: ghcr.io'
    required: true
    default: 'ghcr.io'

  image-name:
    description: Docker image name
    required: true
    
  image-tag:
    description: 'Docker image tag'
    required: true
    
  dockerFile:
    description: 'Path to the Dockerfile'
    default: './Dockerfile'
    required: false
  token:
    description: 'A Github PAT'
    required: true
    
runs:
  using: composite
  steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v2

    - name: Log in to the Container registry 📦
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}

    - name: Scan Docker image 🐳
      uses: snyk/actions/docker@master
      continue-on-error: true
      with:
        image: ${{ inputs.registry }}/${{ inputs.image-name }}:${{ inputs.image-tag }}
        args: --file=${{ inputs.dockerFile }} 
      env:
        SNYK_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Upload Snyk report as sarif 📦
    #   uses: github/codeql-action/upload-sarif@v3
    #   with:
    #     sarif_file: snyk.sarif
