name: "Run Python Unittests"
description: "Set up Python, install dependencies, and run unittests"

inputs:
  test-command:
    description: "Command to run unittests"
    required: false
    default: "python -m unittest discover tests"
  working-directory:
    description: "Working directory for the unittest command"
    required: false
    default: "."
  continue-on-error:
    description: "Continue on error for unittests"
    required: false
    default: "true"


runs:
  using: "composite"
  steps:
      # This step will execute the unittest command and will continue on error if specified
      - name: Run unit tests
        continue-on-error: ${{ inputs.continue-on-error == 'true' }}
        working-directory: ${{ inputs.working-directory }}
        run: |
          echo "📦 Executing unittest command: ${{ inputs.test-command }}"
          # Run the command with proper output redirection
          bash -c "${{ inputs.test-command }} > unittest-report.txt 2>&1" || true

          echo "✅ First few lines of unittest-report.txt:"
          head -n 100 unittest-report.txt || echo "No output"
        shell: bash
      