name: local-k8s
description: Deploy a Docker image to a local Kubernetes cluster.

inputs:
  app-name:
    description: 'Application name'
    required: true
    default: 'netwebapi'
  namespace:  
    description: 'Kubernetes namespace to deploy to'
    required: false
    default: 'default'  
  registry:
    description: 'Container registry. Example: ghcr.io'
    required: true
    default: 'ghcr.io'
  image-name:
    description: Docker image name
    required: true
  image-tag:
    description: 'Docker image tag'
    required: true
  chart: 
    description: 'Helm chart path. If set to "app" this will use the built in helm chart found in this repository'
    required: true
    default: 'app'
  helm-version:
    description: 'Helm version to use: helm or helm3. Default helm3.'
    required: false
    default: 'helm3'
  token:
    description: 'A Github PAT'
    required: true
  
runs:
  using: composite
  steps:
    - uses: actions/checkout@v1
    - name: Deploy to local Kubernetes cluster
      uses: 'deliverybot/helm@v1'
      with:
        release: ${{ inputs.app-name }}
        namespace: ${{ inputs.namespace }}
        chart: ${{ inputs.chart }}
        helm: ${{ inputs.helm-version }}
        token: '${{ github.token }}'
        

