name: deploy-csharp-azure-app-web-services-container
description: Deploy a C# application container to Azure App Service

inputs:
  azure_webapp_name:
    description: 'Azure App Service name'
    required: true
  image-name:
    description: 'The name of the Docker image to deploy'
    required: true
  image-tag:
    description: 'The tag of the Docker image to deploy'
    required: true
  azure_webapp_publish_profile:
    description: 'The publish profile for the Azure Web App Service'
    required: true
        
runs:
  using: composite
  steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@85270a1854658d167ab239bce43949edb336fa7c
      with:
        app-name: ${{ inputs.azure_webapp_name }}
        publish-profile: ${{ inputs.azure_webapp_publish_profile }}
        images: 'ghcr.io/${{ inputs.image-name }}:${{ inputs.image-tag }}'

