name: Package Node Project

inputs:
  package-command:
    description: 'Custom command for packaging (e.g., npm pack, zip, etc.)'
    required: false
    default: 'npm pack'
    type: string
  artifact-name:
    description: 'Name of the uploaded artifact'
    required: false
    default: 'package-artifact'
    type: string
  package-output-dir:
    description: 'Directory where the package is generated (relative to working-directory)'
    required: false
    default: '.'
    type: string



runs:
  using: 'composite'
  steps:
    # This step packages a Node.js project
    - name: Package Project
      id: pack
      run: |
        PACKAGE_FILE=$(npm pack)
        echo "package_file=$PACKAGE_FILE" >> $GITHUB_OUTPUT

    # Upload the package as an artifact
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ steps.pack.outputs.package_file }}
