name: Deploy with Helm
description: Builds and deploys the app using Helm to a Kubernetes cluster.
inputs:
  app-name:
    description: Name of the application to deploy
    required: true
    default: react-app
  kubeconfig:
    description: Base64-encoded kubeconfig to access the cluster
    required: false
  chart-path:
    description: Path to the Helm chart
    required: true
    default: ./charts/react-app
  namespace:
    description: Kubernetes namespace
    required: false
    default: default
  repository:
    description: Docker image repo (e.g., ghcr.io/org/app)
    required: true
    default: latest
  tag:
    description: Docker image tag
    required: true
    default: latest
  ghcr-username:
    description: GitHub Container Registry username
    required: false
  ghcr-pat:
    description: GitHub Container Registry Personal Access Token
    required: false

runs:
  using: composite
  steps:
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: v1.29.0

    - name: Set up Helm
      uses: azure/setup-helm@v3
      with:
        version: v3.14.0

    - name: Create GHCR secret
      if: inputs.ghcr-username != '' && inputs.ghcr-pat != ''
      shell: bash
      run: |
        kubectl create secret docker-registry ghcr-secret \
          --docker-server=ghcr.io \
          --docker-username=${{ inputs.ghcr-username }} \
          --docker-password=${{ inputs.ghcr-pat }} \
          --namespace=${{ inputs.namespace }} \
          --dry-run=client -o yaml | kubectl apply -f -

    - name: Deploy via Helm
      shell: bash
      run: |
        helm upgrade --install ${{ inputs.app-name }} ${{ inputs.chart-path }} \
          --namespace ${{ inputs.namespace }} \
          --create-namespace \
          --set image.repository=${{ inputs.repository }} \
          --set image.tag=${{ inputs.tag }} \
          ${{ inputs.ghcr-username != '' && inputs.ghcr-pat != '' && '--set imagePullSecrets[0].name=ghcr-secret' || '' }}
