name: Lint Node Project

inputs:
  lint-command:
    description: 'Lint command (e.g., npm run lint or npx ng lint)'
    required: false
    default: 'npm run lint'
    type: string
  working-directory:
    description: 'Working directory for the lint command'
    required: false
    default: '.'
    type: string
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
    type: string
  continue-on-error:
    description: 'Continue on error for linting'
    required: false
    default: true
    type: boolean


runs: 
  using: composite
  steps:
    - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/setup@patch-1
      with:
        node-version: ${{ inputs.node-version }}
        working-directory: ${{ inputs.working-directory }}

    # This step runs the lint command
    - name: Lint Project
      run: ${{ inputs.lint-command }}
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      shell: bash

    - name: ESLint Summary
      run: |
        if [[ ! -f eslint-report.json ]]; then
          echo "## 🧹 ESLint Report" > summary.md
          echo "- ⚠️ No report file found. Was ESLint run with JSON output?" >> summary.md
        else
          ERRORS=$(jq '[.[] | .messages[] | select(.severity==2)] | length' eslint-report.json)
          WARNINGS=$(jq '[.[] | .messages[] | select(.severity==1)] | length' eslint-report.json)

          echo "## 🧹 ESLint Report" > summary.md
          echo "- ❌ Errors: $ERRORS" >> summary.md
          echo "- ⚠️ Warnings: $WARNINGS" >> summary.md
        fi
      shell: bash

    - name: Upload ESLint Summary
      uses: actions/upload-artifact@v4
      with:
        name: eslint-summary
        path: summary.md