name: Lint Node Project

inputs:
  lint-command:
    description: 'Lint command (e.g., npm run lint or npx ng lint)'
    required: false
    default: 'npm run lint'
    type: string
  working-directory:
    description: 'Working directory for the lint command'
    required: false
    default: '.'
    type: string
  node-version:
    description: 'Node.js version to use'
    required: false
    default: '20'
    type: string


runs: 
  using: composite
  steps:
    - uses: actions/checkout@v4
      with:
          fetch-depth: 0
    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: 'https://registry.npmjs.org/'

    # Install dependencies
    - name: Install dependencies
      run: npm ci
      shell: bash

    # This step runs the lint command
    - name: Lint Project
      run: ${{ inputs.lint-command }}
      working-directory: ${{ inputs.working-directory }}
      continue-on-error: true
      shell: bash
