name: "Python Linter"
description: "Run linter on Python files"

inputs:
  lint-command:
    description: "Command to execute Pylint"
    required: false
    default: "pylint $(git ls-files '*.py')"
  working-directory:
    description: "Working directory for the linter command"
    required: false
    default: "."


runs:
  using: "composite"
  steps:
    - name: Run Pylint
      shell: bash
      continue-on-error: true
      run: |
        cd "${{ inputs.working-directory }}"
        ${{ inputs.lint-command }}