name: "Python Linter"
description: "Run linter on Python files"

inputs:
  lint-command:
    description: "Command to execute Pylint"
    required: false
    default: "pylint --output-format=text $(git ls-files '*.py')"
  working-directory:
    description: "Working directory for the linter command"
    required: false
    default: "."
  continue-on-error:
    description: "Continue on error for linting"
    required: false
    default: 'true'



runs:
  using: "composite"
  steps:
    # This step runs the linter command in the specified working directory and continues on error if specified
    - name: Run Pylint
      shell: bash
      if: inputs.continue-on-error == 'true'
      continue-on-error: true
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "📦 Executing: ${{ inputs.lint-command }}"
        # Run the command with proper output redirection
        bash -c "${{ inputs.lint-command }} > pylint-report.txt 2>&1" || true

        echo "✅ First few lines of pylint-report.txt:"
        head -n 100 pylint-report.txt || echo "No output"

    - name: Run Pylint
      shell: bash
      if: inputs.continue-on-error != 'true'
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "📦 Executing: ${{ inputs.lint-command }}"
        # Run the command with proper output redirection
        bash -c "${{ inputs.lint-command }} > pylint-report.txt 2>&1" || true

        echo "✅ First few lines of pylint-report.txt:"
        head -n 100 pylint-report.txt || echo "No output"

