name: Docker Publish to GHCR
description: 'Build and push a Docker image to GitHub Container Registry (GHCR)'

inputs:
  token:
    description: 'GitHub token for authentication to GHCR'
    required: true
  registry:
    description: 'Docker registry to push the image to'
    required: false
    default: 'ghcr.io'

outputs:
  tag:
    description: "The new semantic version tag"
    value: ${{ steps.docker-tag.outputs.tag }}


runs:
  using: 'composite'
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Log in to GitHub Container Registry
    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ inputs.registry }}
        username: ${{ github.actor }}
        password: ${{ inputs.token }}
    
    # Convert repository name to lowercase for consistent tagging
    - name: Convert repository name to lowercase
      shell: bash
      id: repo
      run: |
        repo_lower=$(echo "${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]')
        echo "repo=$repo_lower" >> $GITHUB_OUTPUT

    # Set up Docker metadata and build the image
    - name: Set up Docker metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.registry }}/${{ github.repository }}
    
    # Determine the Docker tag based on the event type and branch
    - name: Determine Docker Tag
      id: docker-tag
      shell: bash
      run: |
        DATE=$(date +%Y%m%d)
        RUN_NUMBER=${{ github.run_number }}
        
        if [[ "${{ github.event_name }}" == "pull_request" ]]; then
          PR_NUMBER=${{ github.event.pull_request.number }}
          TAG="PR${PR_NUMBER}-${DATE}.run${RUN_NUMBER}"
        
        elif [[ "${{ github.ref_name }}" == "main" ]]; then
          TAG="main-${DATE}.run${RUN_NUMBER}"
        
        else
          # Sanitize branch name (e.g., strip "feat/", replace slashes)
          BRANCH=$(echo "${{ github.ref_name }}" | sed 's|.*/||' | tr '/' '-')
          TAG="${BRANCH}-${DATE}.run${RUN_NUMBER}"
        fi

        echo "Computed Docker tag: $TAG"
        echo "tag=$TAG" >> "$GITHUB_OUTPUT"
        

    # Build and push the Docker image to GitHub Container Registry
    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          ${{ inputs.registry }}/${{ steps.repo.outputs.repo }}:${{ steps.docker-tag.outputs.tag }}
          ${{ inputs.registry }}/${{ steps.repo.outputs.repo }}:latest
    