name: "Python setup"
description: "Set up Python environment for linting, building, and testing"
inputs:
  python-version:
    description: "Python version to use"
    required: false
    default: '3.11'

  working-directory:
    description: "Project root directory"
    required: false
    default: '.'

  requirements-file:
    description: "Path to the requirements file"
    required: false
    default: 'requirements.txt'


runs:
  using: "composite"
  steps:
    # This step checks out the code from the repository
    - name: Checkout code
      uses: actions/checkout@v4

    # This step sets up the Python environment
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '${{ inputs.python-version }}'

    # This step installs the required Python packages
    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        if [ -f '${{ inputs.requirements-file }}' ]; then pip install -r '${{ inputs.requirements-file }}'; fi