name: Tag creation Workflow
  
on:
  push:
    branches:
      - 'main'
  workflow_dispatch:


jobs:
  # This job handles versioning by generating a new tag based on the commit history
  tag-creation:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      # This step checks out the code from the repository
      - name: Semantic version release
        id: release
        uses: huggingface/semver-release-action@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Use release outputs
        run: |
          echo "Released version: ${{ steps.release.outputs.version }}"
          echo "Tag: ${{ steps.release.outputs.tag }}"
          echo "Was a release created? ${{ steps.release.outputs.released }}"
          echo "Changelog:"
          echo "${{ steps.release.outputs.changelog }}"
