name: Go Build

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      app-name:
        required: true
        type: string
      # main-directory:
      #   required: false
      #   type: string
      #   default: "./cmd"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.2'
          # go-version-file: 'go.mod'

      - name: Go version
        run: go version
        
      - name: Install dependencies and tidy
        run: |
          go mod download
          go mod tidy

      - name: Build binary
        run: |
          go build -o app ./cmd
        # run: |
        #   go build -o ${{ inputs.app-name }} {{inputs.main-directory }}

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: go-binary
          path: app
          # name: ${{ inputs.app-name }}-binary
          # path: ${{ inputs.app-name }}