name: Dev Build Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      app-name:
        required: true
        type: string

jobs:
  setup:
    uses: osru-leu/platform-github-actions/.github/workflows/setup-image-tag.yml@feature/workflows

  lint:
    uses: osru-leu/platform-github-actions/.github/workflows/lint-go.yml@feature/workflows
    with:
      language: ${{ inputs.language }}

  test:
    uses: osru-leu/platform-github-actions/.github/workflows/test-go.yml@feature/workflows
    needs: lint
    with:
      language: ${{ inputs.language }}

  build:
    uses: osru-leu/platform-github-actions/.github/workflows/build-go.yml@feature/workflows
    needs: test
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}

  package:
    uses: osru-leu/platform-github-actions/.github/workflows/package-go.yml@feature/workflows
    needs: [build, setup]
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}
      image-tag: ${{ needs.setup.outputs.image-tag }}

  security:
    uses: osru-leu/platform-github-actions/.github/workflows/security-scan.yml@feature/workflows
    needs: package
    with:
      image-name: ${{ inputs.app-name }}
      image-tag: ${{ needs.setup.outputs.image-tag }}
      languages: ${{ inputs.language }}

  # deploy:
  #   uses: osru-leu/platform-github-actions/.github/workflows/deploy.yml@v1
  #   needs: security
  #   with:
  #     app-name: ${{ inputs.app-name }}
  #     environment: dev
