name: build
on:
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      language:
        required: false
        type: string
        default: 'csharp'
      git-fetch-depth:
        required: false
        type: string
        default: '1'
      dotnet-version:
        required: false
        type: string
        default: '9.0.300'
      dotnet-tools-restore:
        required: false
        type: boolean
        default: true
      dotnet-linter-csharpier:
        required: false
        type: boolean  
        default: true
      dotnet-linter-roslynator:
        required: false
        type: boolean  
        default: false

jobs:     
  lint:
    name: Lint C# code
    if: ${{ inputs.language == 'csharp' }}
    runs-on: 'ubuntu-latest'
    steps:
      - name: csharpier
        if: ${{ inputs.dotnet-linter-csharpier == true }}
        uses: dgeorgievski/my-github-actions/.github/actions/dotnet/lint/csharpier@composites
        with:
          app-name: ${{ inputs.app-name }}
          dotnet-version: ${{ inputs.dotnet-version }}
      - name: roslynator
        if: ${{ inputs.dotnet-linter-roslynator == true }}
        uses: dgeorgievski/my-github-actions/.github/actions/dotnet/lint/roslynator@composites
        with:
          app-name: ${{ inputs.app-name }}
          dotnet-version: ${{ inputs.dotnet-version }}
          restore: ${{ inputs.dotnet-tools-restore }}

  test:
    name: Test ${{ inputs.app-name }}
    needs: lint
    runs-on: 'ubuntu-latest'     
    steps:
      - uses: dgeorgievski/my-github-actions/.github/actions/dotnet/test@composites
        with:
          verbosity: 'normal'
  build:
    name: Build ${{ inputs.app-name }}
    needs: test
    runs-on: 'ubuntu-latest'
    steps:
      - uses: dgeorgievski/my-github-actions/.github/actions/dotnet/build@composites
        with:
          app-name: ${{ inputs.app-name }}
          language: ${{ inputs.language }}
          dotnet-version: ${{ inputs.dotnet-version }}
          git-fetch-depth: ${{ inputs.git-fetch-depth }}   
          token: ${{ secrets.GITHUB_TOKEN }}     
    