name: Complete node Pipeline

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: '20'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string
      
      lint-command:
        description: 'Lint command (e.g., npm run lint)'
        required: false
        default: 'npm run lint'
        type: string

      build-command:
        description: 'build command (e.g., npm run)'
        required: false
        default: 'npm run build'
        type: string

      test-command:
        description: 'test command (e.g., npm test)'
        required: false
        default: 'npm test'
        type: string
        
      package-command:
        description: "Command to package the app"
        required: false
        default: 'npm pack'
        type: string

      artifact-name:
        description: "Name of the build artifact"
        required: false
        default: 'node-package'
        type: string

      contine-on-error:
        description: "Continue on error for linting"
        required: false
        default: true
        type: boolean

jobs:

  # This job runs the linting process to ensure code quality
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/lint@patch-1
        with:
          lint-command: ${{ inputs.lint-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}


  # This job builds the Node.js project, preparing it for packaging
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/build@patch-1
        with:
          build-command: ${{ inputs.build-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          continue-on-error: ${{ inputs.contine-on-error }}
          token: ${{ secrets.GITHUB_TOKEN }}


  # This job executes unit test
  unitTest:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/setup@patch-1
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/jest-unit-test@patch-1
        with:
          test-command: ${{ inputs.test-command }}
          continue-on-error: ${{ inputs.contine-on-error }}

  # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
  securityTest:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/codeql@patch-1
        with:
          languages: javascript
  
  # This job handles versioning by generating a new tag based on the commit history
  versioning:
    runs-on: ubuntu-latest
    needs: [build, unitTest]
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      - id: generate-tag
        uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/git-tag-generation@patch-1

  # This job publishes the Docker image to GitHub Container Registry (GHCR) if a new tag is generated
  publish:
    runs-on: ubuntu-latest
    needs: versioning
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
    steps:
    # This job builds and publishes a Docker image to GitHub Container Registry (GHCR)
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/docker-publish@patch-1
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  dockerScan:
    runs-on: ubuntu-latest
    needs: [versioning, publish]
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    permissions:
      contents: read
      packages: read  # Required to pull from GHCR
    steps:
      # This job scans the Docker image for vulnerabilities using Trivy
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/trivy-scan@patch-1
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'CRITICAL,HIGH'

  # This job packages the Node.js project, creating an artifact for deployment or distribution
  package:
    needs: versioning
    runs-on: ubuntu-latest
    steps:
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/setup@patch-1
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: '.'
      # This step packages the Node.js project
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/git-package@patch-1
        with:
          package-command: ${{ inputs.package-command }}
          artifact-name: ${{ inputs.artifact-name }}


