name: Complete node Pipeline

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: '20'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string
      
      lint-command:
        description: 'Lint command (e.g., npm run lint)'
        required: false
        default: 'npm run lint'
        type: string

      build-command:
        description: 'build command (e.g., npm run)'
        required: false
        default: 'npm run build'
        type: string

      test-command:
        description: 'test command (e.g., npm test)'
        required: false
        default: 'npm test'
        type: string
        
      package-command:
        description: "Command to package the app"
        required: false
        default: 'npm pack'
        type: string

      artifact-name:
        description: "Name of the build artifact"
        required: false
        default: 'node-package'
        type: string

jobs:

  # This job runs the linting process to ensure code quality
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/lint@patch-1
        with:
          lint-command: ${{ inputs.lint-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}


  # This job builds the Node.js project, preparing it for packaging
  build:
    needs: lint
    runs-on: ubuntu-latest
    
    steps:
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/node-templates/build@patch-1
        with:
          build-command: ${{ inputs.build-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
  codeql:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
      - uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/codeql@patch-1
        with:
          languages: javascript
    

  # This job executes unit test
  test:
    needs: build
    uses: KaranbirSinghAhluwalia/platform-github-actions/.github/workflows/unit-test-node.yml@patch-1
    with:
      test-command: ${{ inputs.test-command }}
      node-version: ${{ inputs.node-version }}
      working-directory: ${{ inputs.working-directory }}

  # This job packages the Node.js project, creating an artifact for deployment or distribution
  package:
    needs: [build, test]
    uses: KaranbirSinghAhluwalia/platform-github-actions/.github/workflows/package-node.yml@patch-1
    with:
      working-directory: ${{ inputs.working-directory }}
      package-command: ${{ inputs.package-command }}
      artifact-name: ${{ inputs.artifact-name }}
      package-output-dir: '.'

  versioning:
    needs: [build, test, lint, package]
    uses: KaranbirSinghAhluwalia/platform-github-actions/.github/workflows/auto-version-tag.yml@patch-1

  docker-publish:
    needs: versioning
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    # This job builds and publishes a Docker image to GitHub Container Registry (GHCR)
    uses: KaranbirSinghAhluwalia/platform-github-actions/.github/workflows/docker-publish.yml@patch-1
    with:
      version: ${{ needs.versioning.outputs.new_tag }}
