name: Complete Node Pipeline

on:
  workflow_call:
    secrets:
      TOKEN:
        required: true
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: '20'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string

      lint-command:
        description: 'Lint command (e.g., npm run lint)'
        required: false
        default: 'npm run lint'
        type: string

      build-command:
        description: 'Build command (e.g., npm run build)'
        required: false
        default: 'npm run build'
        type: string

      test-command:
        description: 'Test command (e.g., npm test)'
        required: false
        default: 'npm test'
        type: string

      package-command:
        description: "Command to package the app"
        required: false
        default: 'npm pack'
        type: string

      artifact-name:
        description: "Name of the build artifact"
        required: false
        default: 'node-package'
        type: string

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ inputs.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.working-directory }}

  lint:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint code
        run: ${{ inputs.lint-command }}
        working-directory: ${{ inputs.working-directory }}

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build project
        run: ${{ inputs.build-command }}
        working-directory: ${{ inputs.working-directory }}

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run tests
        run: ${{ inputs.test-command }}
        working-directory: ${{ inputs.working-directory }}

  package:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Package project
        run: ${{ inputs.package-command }}
        working-directory: ${{ inputs.working-directory }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}

  release:
    needs: [build, test, lint, package]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run semantic release
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        run: npx semantic-release
        working-directory: ${{ inputs.working-directory }}
