name: build
on:
  workflow_dispatch:
    inputs:
      language:
        description: 'Programming language of the application'
        required: true
        default: 'csharp'
        type: string
      app-name:
        description: 'Name of the application to package'
        default: 'netwebapi'
        required: true
        type: string
  workflow_call:
    inputs:
      app-name:
        required: true
        type: string
      language:
        required: false
        type: string
        default: 'csharp'
      git-fetch-depth:
        required: false
        type: string
        default: '1'
      dotnet-version:
        required: false
        type: string
        default: '9.0.300'
      dotnet-tools-restore:
        required: false
        type: boolean
        default: true
      dotnet-linter:
        required: false
        type: string  
        default: 'csharpier'

jobs:
  setup:
    name: Setup .NET environment
    runs-on: 'ubuntu-latest'
    steps:
      - uses: dgeorgievski/my-github-actions/.github/actions/common/dotnet/setup@composites
        with:
          dotnet-version: ${{ inputs.dotnet-version }}
          git-fetch-depth: ${{ inputs.git-fetch-depth }}
          
  lint:
    if: ${{ inputs.language == 'csharp' }}
    name: Lint C# code
    needs: setup
    runs-on: 'ubuntu-latest'
    steps:
      - uses: jenseng/dynamic-uses@v1
        with:
          # now you can use expressions 🥳
          uses: dgeorgievski/my-github-actions/.github/actions/common/dotnet/lint/${{inputs.dotnet-linter}}@composites
          # the `with` needs to be converted to a valid json string
          with: '{ "app-name": ${{ inputs.app-name }}, "restore": ${{ inputs.dotnet-tools-restore }}, "dotnet-version": "${{ inputs.dotnet-version }}", "git-fetch-depth": "${{ inputs.git-fetch-depth }}" }'
          
  test:
    if: ${{ inputs.language == 'csharp' }}
    name: Test C# code
    needs: [setup, lint]
    runs-on: 'ubuntu-latest'     
    steps:
      - uses: dgeorgievski/my-github-actions/.github/actions/dotnet/test@composites
        with:
          verbosity: 'detailed'
          
      # - uses: dgeorgievski/my-github-actions/.github/actions/common/dotnet/lint/csharpier@composites
      #   with:
      #     app-name: ${{ inputs.app-name }}
          
    