name: Dev Build Pipeline (Generic - Temporary Backup)

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      app-name:
        required: true
        type: string

jobs:
  setup:
    uses: osru-leu/platform-github-actions/.github/workflows/setup-image-tag.yml@feature/workflows

  # Dynamic approach (doesn't work with cross-repo calls)
  # lint:
  #   uses: osru-leu/platform-github-actions/.github/workflows/lint-${{ inputs.language }}.yml@feature/workflows
  #   with:
  #     language: ${{ inputs.language }}

  # test:
  #   uses: osru-leu/platform-github-actions/.github/workflows/test-${{ inputs.language }}.yml@feature/workflows
  #   needs: lint
  #   with:
  #     language: ${{ inputs.language }}

  # build:
  #   uses: osru-leu/platform-github-actions/.github/workflows/build-${{ inputs.language }}.yml@feature/workflows
  #   needs: test
  #   with:
  #     language: ${{ inputs.language }}
  #     app-name: ${{ inputs.app-name }}

  # package:
  #   uses: osru-leu/platform-github-actions/.github/workflows/package-${{ inputs.language }}.yml@feature/workflows
  #   needs: [build, setup]
  #   with:
  #     language: ${{ inputs.language }}
  #     app-name: ${{ inputs.app-name }}
  #     image-tag: ${{ needs.setup.outputs.image_tag }}

  # Hardcoded approach (works with cross-repo calls)
  lint:
    uses: osru-leu/platform-github-actions/.github/workflows/lint-go.yml@feature/workflows
    with:
      language: ${{ inputs.language }}

  test:
    uses: osru-leu/platform-github-actions/.github/workflows/test-go.yml@feature/workflows
    needs: lint
    with:
      language: ${{ inputs.language }}

  build:
    uses: osru-leu/platform-github-actions/.github/workflows/build-go.yml@feature/workflows
    needs: test
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}

  package:
    uses: osru-leu/platform-github-actions/.github/workflows/package-go.yml@feature/workflows
    needs: [build, setup]
    with:
      language: ${{ inputs.language }}
      app-name: ${{ inputs.app-name }}
      image-tag: ${{ needs.setup.outputs.image_tag }}

  security:
    uses: osru-leu/platform-github-actions/.github/workflows/security-scan.yml@feature/workflows
    needs: [package, setup]
    with:
      image-name: ${{ inputs.app-name }}
      image-tag: ${{ needs.setup.outputs.image_tag }}
      languages: ${{ inputs.language }}

  deploy:
    uses: osru-leu/platform-github-actions/.github/workflows/deploy.yml@feature/workflows
    needs: security
    with:
      app-name: ${{ inputs.app-name }}
      environment: dev
      image-tag: ${{ needs.setup.outputs.image_tag }} 