name: Complete Java Pipeline

on:
  workflow_call:
    inputs:
      java-version:
        description: "Java version to use"
        required: false
        default: '17'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string
      
      lint-command:
        description: 'Lint command (e.g., mvn checkstyle:check)'
        required: false
        default: 'mvn spring-javaformat:validate'
        type: string

      build-command:
        description: 'Build command (e.g., mvn clean package)'
        required: false
        default: 'mvn clean package'
        type: string

      test-command:
        description: 'test command (e.g., mvn test)'
        required: false
        default: 'mvn test'
        type: string

      artifact-name:
        description: "Name of the build artifact"
        required: false
        default: 'java-package'
        type: string
      
      run-trivy:
        description: 'Run Trivy Scan'
        required: false
        default: true
        type: boolean

      run-grype:
        description: 'Run Grype Scan'
        required: false
        default: true
        type: boolean

      contine-on-error:
        description: "Continue on error for linting"
        required: false
        default: true
        type: boolean

      create-artifact:
        description: "Create build artifact (legacy mode)"
        required: false
        default: false
        type: boolean

      build-docker:
        description: "Build and push Docker image"
        required: false
        default: false
        type: boolean

permissions:
  actions: read
  contents: write
  security-events: write
  packages: write

jobs:
  # This job runs the linting process to ensure code quality
  lint:
    runs-on: ubuntu-latest
    steps:
      # This step sets up the Java environment
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/java/setup@v0
        with:
          java-version: ${{ inputs.java-version }}
          working-directory: ${{ inputs.working-directory }}

      # This job sets up Java and runs the lint command
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/java/lint@v0
        with:
          lint-command: ${{ inputs.lint-command }}
          java-version: ${{ inputs.java-version }}
          working-directory: ${{ inputs.working-directory }}
          continue-on-error: ${{ inputs.contine-on-error }}
          create-artifact: ${{ inputs.create-artifact }}

  # This job executes unit tests
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # This step sets up the Java environment
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/java/setup@v0
        with:
          java-version: ${{ inputs.java-version }}
          working-directory: ${{ inputs.working-directory }}
          
      # This step runs the unit tests using the new Java test action
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/java/test@v0
        with:
          test-command: ${{ inputs.test-command }}
          java-version: ${{ inputs.java-version }}
          working-directory: ${{ inputs.working-directory }}
          continue-on-error: ${{ inputs.contine-on-error }}
          create-artifact: ${{ inputs.create-artifact }}

  # This job builds the Java project and optionally creates Docker image
  build:
    needs: unit-test
    runs-on: ubuntu-latest
    outputs:
      docker-tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
      # This step sets up the Java environment
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/java/setup@v0
        with:
          java-version: ${{ inputs.java-version }}
          working-directory: ${{ inputs.working-directory }}

      # This step builds and packages the Java project
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/java/build@v0
        with:
          build-command: ${{ inputs.build-command }}
          java-version: ${{ inputs.java-version }}
          working-directory: ${{ inputs.working-directory }}
          artifact-name: ${{ inputs.artifact-name }}
          create-artifact: ${{ inputs.create-artifact }}

      # Generate version tag if Docker build is requested
      - id: generate-tag
        if: ${{ inputs.build-docker }}
        uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-tag-generation@v0

      # Build and push Docker image if requested
      - id: docker-tag
        if: ${{ inputs.build-docker }}
        uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/docker-build-push@v0
        with:
          version: ${{ steps.generate-tag.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

  # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
  # Note: CodeQL is only available for public repos or private repos with GitHub Advanced Security
  security-scan:
    needs: lint
    runs-on: ubuntu-latest
    if: ${{ github.repository_visibility == 'public' }}
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
      - name: Run CodeQL Analysis
        uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/codeql@v0
        with:
          languages: java
        continue-on-error: true

  # This job scans the Docker image for vulnerabilities using Trivy and Grype
  docker-scan:
    runs-on: ubuntu-latest
    needs: [build]
    if: ${{ needs.build.outputs.docker-tag != '' }}
    permissions:
      contents: read
      packages: read 
    steps:
      # This job scans the Docker image for vulnerabilities using Trivy
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/trivy-scan@v0
        if: ${{ inputs.run_trivy == 'true' }}
        with:
          version: ${{ needs.build.outputs.docker-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'CRITICAL,HIGH'

      # This job summarizes the Trivy report and writes it to GITHUB_STEP_SUMMARY
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-dashboard@v0
        if: ${{ inputs.run_trivy == 'true' }}
        with:
          tool: Trivy
          title: Trivy Vulnerability Report
          report: trivy-report.txt
          format: text
          max-lines: 100

      # This job scans the Docker image for vulnerabilities using Grype
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/grype-scan@v0
        if: ${{ inputs.run_grype == 'true' }}
        with:
          version: ${{ needs.build.outputs.docker-tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # This job summarizes the Grype report and writes it to GITHUB_STEP_SUMMARY
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-dashboard@v0
        if: ${{ inputs.run_grype == 'true' }}
        with:
          tool: Grype
          title: Grype Vulnerability Report
          report: grype-report.txt
          max-lines: 100 