name: Lint Go Code

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
    #   version:
    #     required: true
    #     type: string

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24' # make dynamic ${{ inputs.version }}
          cache: false

      - name: Run StaticCheck
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: false
          output-format: stylish

