name: Lint Node Project

on:
  workflow_call:
    inputs:
      lint-command:
        description: 'Lint command (e.g., npm run lint or npx ng lint)'
        required: false
        default: 'npm run lint'
        type: string

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # This step runs the lint command
      - name: Lint Project
        run: ${{ inputs.lint-command }}
