name: Node.js Release Workflow
  
on:
  workflow_call:

jobs:
  # This job handles versioning by generating a new tag based on the commit history
  versioning:
    runs-on: ubuntu-latest
    needs: [build, unit-test]
    permissions:
      contents: write
    steps:
      # This step checks out the code from the repository
      - id: generate-tag
        uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/github-actions/git-tag-generation@testing
        with:
          token: ${{ secrets.GITHUB_TOKEN }}