name: Complete node Pipeline

on:
  workflow_call:
    secrets:
      GHCR_PAT:
        required: true
      GHCR_USERNAME:
        required: true

jobs:
  deploy:
    runs-on: [self-hosted, macOS, ARM64]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.29.0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.14.0

      - name: Docker login to GHCR
        run: |
          echo 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 | docker login ghcr.io -u karanbirsinghahluwalia --password-stdin

      - name: Deploy to Local CNOE Cluster
        run: |
          helm upgrade --install reactapp ./charts/templates \
            --namespace reactapp \
            --create-namespace \
            --set image.repository=ghcr.io/karanbirsinghahluwalia/reactapp \
            --set image.tag=v0.1.35
