name: Complete node Pipeline

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version to use"
        required: false
        default: '20'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string
      
      lint-command:
        description: 'Lint command (e.g., npm run lint)'
        required: false
        default: 'npm run lint'
        type: string
      
      registry:
        description: 'Docker registry to push the image (e.g., ghcr.io/org/app)'
        required: false
        default: 'ghcr.io'
        type: string

      build-command:
        description: 'build command (e.g., npm run)'
        required: false
        default: 'npm run build'
        type: string

      test-command:
        description: 'test command (e.g., npm test)'
        required: false
        default: 'npm test'
        type: string
        
      package-command:
        description: "Command to package the app"
        required: false
        default: 'npm pack'
        type: string

      artifact-name:
        description: "Name of the build artifact"
        required: false
        default: 'node-package'
        type: string
      
      run-trivy:
        description: 'Run Trivy Scan'
        required: false
        default: 'true'
        type: string

      run-grype:
        description: 'Run Grype Scan'
        required: false
        default: 'true'
        type: string

      continue-on-error:
        description: "Continue on error for linting"
        required: false
        default: 'true'
        type: string

jobs:
  # This job runs the linting process to ensure code quality
  lint:
    runs-on: ubuntu-latest
    steps:
    # This job sets up Node.js and runs the lint command
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/setup@v0
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}

      # This job sets up Node.js and runs the lint command
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/lint@v0
        with:
          lint-command: ${{ inputs.lint-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          continue-on-error: ${{ inputs.continue-on-error }}

      # This job summarizes the build report and writes it to GITHUB_STEP_SUMMARY
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-dashboard@v0
        with:
          tool: ESLint
          title: Lint Report (JSON)
          report: eslint-report.json
          format: eslint-json
          max-lines: 100


  # This job builds the Node.js project, preparing it for packaging
  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # This job sets up Node.js in the environment
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/setup@v0
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}  

      # This job sets up Node.js and runs the build command
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/build@v0
        with:
          build-command: ${{ inputs.build-command }}
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
          token: ${{ secrets.GITHUB_TOKEN }}
        

  # This job executes unit test
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # This job sets up Node.js and runs unit tests
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/setup@v0
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
      # This step runs the unit tests using Jest
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/jest-unit-test@v0
        with:
          test-command: ${{ inputs.test-command }}
          continue-on-error: ${{ inputs.continue-on-error }}
      
      # This job summarizes the Jest report and writes it to GITHUB_STEP_SUMMARY
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-dashboard@v0
        with:
          tool: Jest
          title: Unit Test Results
          report: jest-report.json
          format: auto
          max-lines: 100


  # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
  security-scan:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      # This job sets up Node.js and runs unit tests
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/node/setup@v0
        with:
          node-version: ${{ inputs.node-version }}
          working-directory: ${{ inputs.working-directory }}
      # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/static-code-analysis/codeql@v0
        with:
          languages: JavaScript
          working-directory: ${{ inputs.working-directory }}
          continue-on-error: ${{ inputs.continue-on-error }}
      
      # This job summarizes the CodeQL report and writes it to GITHUB_STEP_SUMMARY
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-dashboard@v0
        with:
          tool: CodeQL
          title: Security Issues
          report: codeql-results.sarif
          format: sarif
          max-lines: 100

  # This job publishes the Docker image to GitHub Container Registry (GHCR) if a new tag is generated
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: [build, unit-test]
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
    outputs:
      tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
    # This job builds and publishes a Docker image to GitHub Container Registry (GHCR)
      - id: docker-tag
        uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/docker-build-push@v0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.registry }}

  # This job scans the Docker image for vulnerabilities using Trivy and Grype
  docker-scan:
    runs-on: ubuntu-latest
    needs: [docker-build-and-push]
    if: ${{ needs.docker-build-and-push.outputs.tag != '' }}
    permissions:
      contents: read
      packages: read 
    steps:
      # This job scans the Docker image for vulnerabilities using Trivy
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/trivy-scan@v0
        if: ${{ inputs.run-trivy == 'true' }}
        with:
          version: ${{ needs.docker-build-and-push.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'CRITICAL,HIGH'

      # This job summarizes the Trivy report and writes it to GITHUB_STEP_SUMMARY
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-dashboard@v0
        if: ${{ inputs.run-trivy == 'true' }}
        with:
          tool: Trivy
          title: Trivy Vulnerability Report
          report: trivy-report.txt
          format: text
          max-lines: 100

      # This job scans the Docker image for vulnerabilities using Grype
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/grype-scan@v0
        if: ${{ inputs.run-grype == 'true' }}
        with:
          version: ${{ needs.docker-build-and-push.outputs.tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

      # This job summarizes the Grype report and writes it to GITHUB_STEP_SUMMARY
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-dashboard@v0
        if: ${{ inputs.run-grype == 'true' }}
        with:
          tool: Grype
          title: Grype Vulnerability Report
          report: grype-report.txt
          max-lines: 100

