name: Package Go Application

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      app-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
    outputs:
      image-tag:
        description: "The Docker image tag"
        value: ${{ jobs.package.outputs.image-tag }}

jobs:
  package:
    runs-on: ubuntu-latest
    outputs:
      image-tag: ${{ inputs.image-tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download binary artifact
        uses: actions/download-artifact@v4
        with:
          name: go-binary
          path: ./

      - name: Make binary executable
        run: chmod +x app

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ inputs.app-name }}:${{ inputs.image-tag }}
          outputs: type=docker,dest=/tmp/${{ inputs.app-name }}.tar

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.app-name }}-image
          path: /tmp/${{ inputs.app-name }}.tar
