name: Complete python Pipeline

on:
  workflow_call:
    inputs:
      python-version:
        description: "Python version to use"
        required: false
        default: '3.9'
        type: string

      working-directory:
        description: "Project root directory"
        required: false
        default: '.'
        type: string
      
      registry:
        description: 'Docker registry to push the image (e.g., ghcr.io/org/app)'
        required: false
        default: 'ghcr.io'
        type: string
      
      lint-command:
        description: 'Lint command (e.g., npm run lint)'
        required: false
        default: 'pylint app run.py tests'
        type: string

      test-command:
        description: 'test command (e.g., npm test)'
        required: false
        default: 'python -m unittest discover tests'
        type: string
        
      package-command:
        description: "Command to package the app"
        required: false
        default: 'python -m build'
        type: string

      package-output:
        description: "Directory or file path to upload as package artifact"
        required: false
        default: 'dist/'
        type: string

      artifact-name:
        description: "Name of the uploaded artifact"
        required: false
        default: 'python-package'
        type: string
      
      run_trivy:
        description: 'Run Trivy Scan'
        required: false
        default: true
        type: boolean

      run_grype:
        description: 'Run Grype Scan'
        required: false
        default: true
        type: boolean

      contine-on-error:
        description: "Continue on error for linting"
        required: false
        default: true
        type: boolean

permissions:
  actions: read
  contents: write
  security-events: write
  packages: write

jobs:
  # This job runs the linting process to ensure code quality
  lint:
    runs-on: ubuntu-latest
    steps:
    # This job sets up Node.js and runs the lint command
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/python/setup@v0
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}

      # This job sets up Node.js and runs the lint command
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/python/lint@v0
        with:
          lint-command: ${{ inputs.lint-command }}
          continue-on-error: ${{ inputs.contine-on-error }}

  # This job executes unit test
  unit-test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      # This job sets up Python and runs unit tests
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/python/setup@v0
        with:
          python-version: ${{ inputs.python-version }}
          working-directory: ${{ inputs.working-directory }}
      # This step runs the unit tests using Jest
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/python/unittest@v0
        with:
          test-command: ${{ inputs.test-command }}
          continue-on-error: ${{ inputs.continue-on-error }}
  
  # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
  security-scan:
    needs: lint
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    steps:
      # This job runs CodeQL analysis to identify security vulnerabilities and code quality issues
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/static-code-analysis/codeql@v0
        with:
          languages: python
          working-directory: ${{ inputs.working-directory }}

  # This job builds the Python project, preparing it for packaging
  versioning:
    runs-on: ubuntu-latest
    needs: [lint, unit-test]
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      # This step checks out the code from the repository
      - id: generate-tag
        uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/git-tag-generation@v0


  # This job publishes the Docker image to GitHub Container Registry (GHCR) if a new tag is generated
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: versioning
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
    steps:
    # This job builds and publishes a Docker image to GitHub Container Registry (GHCR)
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/docker-build-push@v0
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.registry }}
  
  # This job scans the Docker image for vulnerabilities using Trivy and Grype
  docker-scan:
    runs-on: ubuntu-latest
    needs: [versioning, docker-build-and-push]
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    permissions:
      contents: read
      packages: read  # Required to pull from GHCR
    steps:
      # This job scans the Docker image for vulnerabilities using Trivy
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/trivy-scan@v0
        if: ${{ inputs.run_trivy == true }}
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'CRITICAL,HIGH'
  
      # This job scans the Docker image for vulnerabilities using Grype
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/grype-scan@v0
        if: ${{ inputs.run_grype == true }}
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
