name: Node.js Release Workflow
  
on:
  workflow_call:

jobs:
  # This job handles versioning by generating a new tag based on the commit history
  versioning:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      new_tag: ${{ steps.generate-tag.outputs.tag }}
    steps:
      # This step checks out the code from the repository
      - id: generate-tag
        uses: KaranbirSinghAhluwalia/platform-github-actions/.github/actions/common/github-actions/git-tag-generation@testing
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
  
  # This job publishes the Docker image to GitHub Container Registry (GHCR) if a new tag is generated
  docker-build-and-push:
    runs-on: ubuntu-latest
    needs: versioning
    if: ${{ needs.versioning.outputs.new_tag != '' }}
    permissions:
      contents: read
      packages: write  # Required to push to GHCR
    outputs:
      tag: ${{ steps.docker-tag.outputs.tag }}
    steps:
    # This job builds and publishes a Docker image to GitHub Container Registry (GHCR)
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/docker-build-push@v0
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          registry: ${{ inputs.registry }}

  docker-scan:
    runs-on: ubuntu-latest
    needs: [docker-build-and-push]
    if: ${{ needs.docker-build-and-push.outputs.tag != '' }}
    permissions:
      contents: read
      packages: read 
    steps:
      # This job scans the Docker image for vulnerabilities using Trivy
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/trivy-scan@v0
        if: ${{ inputs.run_trivy == true }}
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          severity: 'CRITICAL,HIGH'
      
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/github-dashboard@v0
        if: ${{ inputs.run_trivy == true }}
        with:
          tool: 'Trivy'
          report: 'trivy-report.txt'
          critical_keyword: 'CRITICAL'
          high_keyword: 'HIGH'

      # This job scans the Docker image for vulnerabilities using Grype
      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/security-scanner/grype-scan@v0
        if: ${{ inputs.run_grype == true }}
        with:
          version: ${{ needs.versioning.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/actions/common/github-actions/github-dashboard@v0
        if: ${{ inputs.run_grype == true }}
        with:
          tool: 'Grype'
          report: 'grype-report.txt'
          critical-keyword: 'CRITICAL'
          high-keyword: 'HIGH'