name: "CodeQL"

on:
  workflow_call:
    inputs:
      image-name:
        required: true
        type: string
      image-tag:
        required: true
        type: string
      languages:
        required: true
        type: string

jobs:
  analyze:
    name: Analyze with CodeQL
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.lang-matrix.outputs.matrix }}

    permissions:
      security-events: write
      actions: read
      contents: read

    steps:
      - name: checkout repository
        uses: actions/checkout@v3

      - name: Set up language matrix
        id: lang-matrix
        run: |
          LANGS="${{ inputs.languages }}"
          echo "matrix=$(echo $LANGS | tr ',' '\n' | jq -R -s -c 'split(\"\n\") | map(select(length > 0))')" >> $GITHUB_OUTPUT

      - name: Debug matrix
        run: echo "${{ steps.lang-matrix.outputs.matrix }}"

  scan:
    needs: analyze
    runs-on: ubuntu-latest
    strategy:
      matrix:
        language: ${{ fromJson(needs.analyze.outputs.matrix)  }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Initialize CodeQL
        uses:  github/codeql-action/init@v3
        with: 
          language: ${{ matrix.language }}

      - name: Build
        run: |
          if [[ "${{ matrix.language }}" == "go" || "${{ matrix.language }}" == "golang" ]]; then
            go build ./...
          elif [[ "${{ matrix.language }}" == "python" ]]; then
            echo "No build needed for Python"
          elif [[ "${{ matrix.language }}" == "csharp" ]]; then
            dotnet build
          elif [[ "${{ matrix.language }}" ==  "javascript" ]]; then
            npm ci
            npm run build || true
          else
            echo "Unsupported language: ${{ matrix.language }}"
            exit 1
          fi

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  container-scan:
    runs-on: ubuntu-latest
    needs: analyze
    steps:
      - name: Download container image
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.image-name }}-image
          path: /tmp/

      - name: Run Trivy vulnerability scanner on OCI archive
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'image'
          image-ref: 'oci-archive:/tmp/${{ inputs.image-name }}.tar'
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Generate security report
        run: |
          echo "Container security scan completed for ${{ inputs.image-name }}:${{ inputs.image-tag }}"