name: test CI/CD for .NET
on:
  workflow_dispatch:
    inputs:
      app-name:
        required: true
        default: 'netwebapi'
        description: 'Application name to deploy'
        type: string
      language:
        required: false
        description: 'Programming language of the application'
        type: string
        default: 'csharp'
      git-fetch-depth:
        required: false
        description: 'Git fetch depth for the repository'
        type: string
        default: '1'
      
jobs:     
  deploy:
    name: Deploy ${{ inputs.app-name }}

    runs-on: ['self-hosted', 'macOS']
    steps:
      - uses: dgeorgievski/my-github-actions/.github/actions/dotnet/deploy/local-k8s-helm@composites
        with:
          app-name: ${{ inputs.app-name }}
          namespace: ${{ inputs.app-name }}
          registry: ghcr.io
          image-name: 'dgeorgievski/${{ inputs.app-name }}'
          image-tag: '1.8.0'
          chart: 'deploy/helm/netwebapi'
