name: Node.js Unit Tests

on:
  workflow_call:
    inputs:
      test-command:
        description: "Command to run unit tests"
        required: false
        default: 'npm test'
        type: string

    outputs:
      coverage-report:
        description: "Coverage report file"
        value: coverage/cobertura-coverage.xml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # This step will used to run unit test
      - name: Run Unit Tests
        run: ${{ inputs.test-command }}

      # This step will be used to publish coverage report
      - name: Upload Coverage Report
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
