name: Dev Build Pipeline

on:
  workflow_call:
    inputs:
      language:
        required: true
        type: string
      app-name:
        required: true
        type: string
  push:
    branches-ignore:
      - 'release/**'
    tags-ignore:
      - '**'

jobs:
  setup:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/setup-image-tag.yml@v1
    outputs:
      image-tag: ${{ steps.set-tag.outputs.image_tag }}

  lint:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/lint-${{ inputs.language }}.yml@v1
    with: ${{ inputs }}

  test:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/test-${{ inputs.language }}.yml@v1
    needs: lint
    with: ${{ inputs }}

  build:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/build-${{ inputs.language }}.yml@v1
    needs: test
    with: ${{ inputs }}

  package:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/package-${{ inputs.language }}.yml@v1
    needs: build
    with: ${{ inputs }}

  security:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/security-scan.yml@v1
    needs: package
    with:
      image-name: my-app
      image-tag: ${{ needs.setup.outputs.image-tag }}

  deploy:
    uses: altimetrik-digital-enablement-demo-hub/platform-github-actions/.github/workflows/deploy.yml@v1
    needs: security
    with:
      app-name: ${{ inputs.app-name }}
      environment: dev
